---

## Base configuration for Sonoff Pow R2
esphome:
  platform: ESP8266
  board: esp01_1m


# Disable logging via UART (used by power monitor)
logger:
  baud_rate: 0


uart:
  rx_pin: RX
  baud_rate: 4800


## Inputs
binary_sensor:
  - id: sonoff_pow_r2_button
    platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: true
    name: "Button"
    disabled_by_default: true


## Outputs
output:
  - id: sonoff_pow_r2_blue_led_pwm
    platform: esp8266_pwm
    pin:
      number: GPIO13
      inverted: true


## Lights
light:
  - id: sonoff_pow_r2_blue_led
    platform: monochromatic
    name: "Blue LED"
    output: sonoff_pow_r2_blue_led_pwm
    disabled_by_default: true


## Switches
switch:
  - id: sonoff_pow_r2_relay
    platform: template
    name: "Relay"
    optimistic: true
    turn_on_action:
      - switch.turn_on: sonoff_pow_r2_relay_internal
    turn_off_action:
      - switch.turn_off: sonoff_pow_r2_relay_internal

  - id: sonoff_pow_r2_relay_internal
    platform: gpio
    internal: true
    pin: GPIO12


## Sensors
sensor:
  # Power sensor
  - platform: cse7766
    current:
      id: sonoff_pow_r2_current
      name: "Current"
      disabled_by_default: true
      filters: &cse7766-filter
        - throttle_average: 10s
    voltage:
      id: sonoff_pow_r2_voltage
      name: "Voltage"
      disabled_by_default: true
      filters: *cse7766-filter
    power:
      id: sonoff_pow_r2_power
      name: "Power"
      filters: *cse7766-filter
    energy:
      id: sonoff_pow_r2_energy
      name: "Energy"
      disabled_by_default: true
      filters: *cse7766-filter

  # Daily energy
  - platform: total_daily_energy
    name: "Total Daily Energy"
    power_id: sonoff_pow_r2_power
    filters:
      - multiply: 0.001
    unit_of_measurement: kWh
    device_class: energy
