---

## Display status on RGB LED
# Slow pulse when no WiFi
# Fast pulse when no connection to home-assistant/MQTT
light:
  - id: !extend sonoff_pow_r2_blue_led
    effects:
      - pulse:
          name: pulse_slow
          transition_length: 1s
          update_interval: 1s
      - pulse:
          name: pulse_fast
          transition_length: 0.5s
          update_interval: 0.5s


interval:
  - interval: 5s
    then:
      if:
        condition:
          wifi.connected:
        then:
          - if:
              condition:
                binary_sensor.is_on: core_status
              then:
                - light.turn_on:
                    id: sonoff_pow_r2_blue_led
                    transition_length: 0.1s
                - delay: 0.2s
                - light.turn_off:
                    id: sonoff_pow_r2_blue_led
                    transition_length: 0.1s
              else:
                - light.turn_on:
                    id: sonoff_pow_r2_blue_led
                    effect: pulse_fast
        else:
          - light.turn_on:
              id: sonoff_pow_r2_blue_led
              effect: pulse_slow
