---

## Include universal configuration
packages:
  # esphome configuration
  core_esphome: !include core/esphome.yaml

  # SNTP
  core_sntp: !include core/sntp.yaml

  # WiFi credentials
  core_wifi: !include core/wifi.yaml

  # Connection sensor
  core_status: !include core/status.yaml

  # Sensors
  core_power: !include power.yaml
  core_uptime: !include uptime.yaml
  core_wifi_sensor: !include wifi_sensor.yaml

  # HTTP requests
  core_http_request: !include core/http_request.yaml

  # OTA updates
  core_ota: !include core/ota.yaml
