---

## Power/restart command buttons
button:
  - platform: restart
    name: "Restart"
    entity_category: diagnostic

  - platform: shutdown
    name: "Shutdown"
    entity_category: diagnostic
    disabled_by_default: true

  - platform: safe_mode
    name: "Restart (Safe Mode)"
    entity_category: diagnostic
    disabled_by_default: true

  - platform: factory_reset
    name: "Restart (Factory Default)"
    entity_category: diagnostic
    disabled_by_default: true
