---

## Power/restart command buttons
button:
  - platform: restart
    name: "${friendly_name} Restart"
    entity_category: diagnostic
    disabled_by_default: true

  - platform: shutdown
    name: "${friendly_name} Shutdown"
    entity_category: diagnostic
    disabled_by_default: true

  - platform: safe_mode
    name: "${friendly_name} Restart (Safe Mode)"
    entity_category: diagnostic
    disabled_by_default: true

  - platform: factory_reset
    name: "${friendly_name} Restart (Factory Default)"
    entity_category: diagnostic
    disabled_by_default: true
