---

## Standalone Web Server
# https://esphome.io/components/http_request.html
web_server:
  port: 80
  auth:
    username: !secret web_server_auth_username
    password: !secret web_server_auth_password
