---

sensor:
  ## WiFi Signal Sensor
  # https://esphome.io/components/sensor/wifi_signal.html
  - platform: wifi_signal
    name: "WiFi Signal"
    update_interval: 300s
    entity_category: diagnostic


text_sensor:
  ## WiFi Info Text Sensor
  # https://esphome.io/components/text_sensor/wifi_info.html
  - platform: wifi_info
    ip_address:
      name: "IP Address"
      id: wifi_ip
      entity_category: diagnostic

    ssid:
      name: "Connected SSID"
      id: wifi_ssid
      disabled_by_default: true
      entity_category: diagnostic

    bssid:
      name: "Connected BSSID"
      id: wifi_bssid
      disabled_by_default: true
      entity_category: diagnostic

    mac_address:
      name: "MAC Address"
      id: wifi_mac
      entity_category: diagnostic
