---

## Base configuration for Athom E27 7W Bulb
# Ref: https://devices.esphome.io/devices/Athom-E27-7W-Bulb
esp8266:
  board: esp8285
  restore_from_flash: true


output:
  - platform: esp8266_pwm
    id: athom_e27_7w_output_red
    pin: GPIO4

  - platform: esp8266_pwm
    id: athom_e27_7w_output_green
    pin: GPIO12

  - platform: esp8266_pwm
    id: athom_e27_7w_output_blue
    pin: GPIO14

  - platform: esp8266_pwm
    id: athom_e27_7w_output_warm_white
    pin: GPIO13

  - platform: esp8266_pwm
    id: athom_e27_7w_output_white
    pin: GPIO5


light:
  - platform: rgbww
    name: None
    icon: "${device_icon}"
    id: athom_e27_7w_light
    red: athom_e27_7w_output_red
    green: athom_e27_7w_output_green
    blue: athom_e27_7w_output_blue
    warm_white: athom_e27_7w_output_warm_white
    cold_white: athom_e27_7w_output_white
    cold_white_color_temperature: 6000 K
    warm_white_color_temperature: 3000 K
    color_interlock: true
    restore_mode: ALWAYS_ON
