---

button:
  - platform: template
    id: sonoff_pow_r2_button_cycle
    name: "Power Cycle"
    icon: "mdi:restart-alert"
    on_press:
      - script.execute: sonoff_pow_r2_power_cycle


binary_sensor:
  - id: !extend sonoff_pow_r2_button
    on_press:
      button.press: sonoff_pow_r2_button_cycle


script:
  - id: sonoff_pow_r2_power_cycle
    mode: restart
    then:
      - switch.turn_off: sonoff_pow_r2_relay
      - delay: 5 sec
      - switch.turn_on: sonoff_pow_r2_relay
