---

substitutions:
  # Device name and identifier (internal)
  device_name: hall-ac
  device_id: hall_ac

  # Friendly name for UI
  friendly_name: Hall Air Conditioner

  # IP address
  device_ip: !secret ip_hall_aircon


packages:
  # Core
  core: !include packages/core_mqtt.yaml

  # Remote access
  web_server: !include packages/web_server.yaml

  # iBeacon
  ibeacon: !include
    file: packages/ibeacon.yaml
    vars:
      ibeacon_major: !secret ibeacon_major_upstairs
      ibeacon_minor: !secret ibeacon_minor_upstairs_hall

  # Hardware specific
  hardware_base: !include packages/hardware/m5stack_atom/base.yaml
  hardware_status: !include packages/hardware/m5stack_atom/status.yaml
  hardware_ir: !include packages/hardware/m5stack_atom/remote_transmitter-ir.yaml

  # Utilities
  manual_ir: !include packages/manual_ir_lg.yaml


esphome:
  comment: "Hall air-conditioner"


climate:
  - id: ${device_id}_climate
    platform: heatpumpir
    name: "Hall Air-Conditioner"
    protocol: panasonic_jke
    horizontal_default: left
    vertical_default: up
    min_temperature: 16
    max_temperature: 30
    on_state:
      - if:
          condition:
            lambda: 'return id(${device_id}_climate).mode == climate::CLIMATE_MODE_OFF;'
          then:
            - logger.log: "Off"
            - light.turn_off:
                id: ${device_id}_led
          else:
            - if:
                condition:
                  lambda: 'return id(${device_id}_climate).mode == climate::CLIMATE_MODE_HEAT_COOL;'
                then:
                  - logger.log: "Auto"
                  - light.turn_on:
                      id: ${device_id}_led
                      brightness: 100%
                      red: 100%
                      green: 0%
                      blue: 100%
                else:
                  - if:
                      condition:
                        lambda: 'return id(${device_id}_climate).mode == climate::CLIMATE_MODE_COOL;'
                      then:
                        - logger.log: "Cooling"
                        - light.turn_on:
                            id: ${device_id}_led
                            brightness: 100%
                            red: 0%
                            green: 0%
                            blue: 100%
                      else:
                        - if:
                            condition:
                              lambda: 'return id(${device_id}_climate).mode == climate::CLIMATE_MODE_HEAT;'
                            then:
                              - logger.log: "Heating"
                              - light.turn_on:
                                  id: ${device_id}_led
                                  brightness: 100%
                                  red: 100%
                                  green: 0%
                                  blue: 0%
                            else:
                              - if:
                                  condition:
                                    lambda: 'return id(${device_id}_climate).mode == climate::CLIMATE_MODE_DRY;'
                                  then:
                                    - logger.log: "Drying"
                                    - light.turn_on:
                                        id: ${device_id}_led
                                        brightness: 100%
                                        red: 100%
                                        green: 50%
                                        blue: 0%
                                  else:
                                    - logger.log: "Other"
                                    - light.turn_on:
                                        id: ${device_id}_led
                                        brightness: 100%
                                        red: 100%
                                        green: 100%
                                        blue: 100%


binary_sensor:
  # Push button
  - id: !extend ${device_id}_button
    on_press:
      - climate.control:
          id: ${device_id}_climate
          mode: "OFF"
