---

substitutions:
  # Device name and identifier (internal)
  device_name: hall-ac

  # Friendly name for UI
  friendly_name: Hall Air Conditioner

  # IP address
  device_ip: !secret ip_hall_aircon


packages:
  # Core
  core: !include packages/core_mqtt.yaml

  # Remote access
  web_server: !include packages/web_server.yaml

  # Hardware specific
  hardware_base: !include packages/hardware/m5stack_atom/base.yaml
  hardware_status: !include packages/hardware/m5stack_atom/status.yaml
  hardware_ir: !include packages/hardware/m5stack_atom/ir.yaml

  # Utilities
  manual_ir: !include packages/hardware/m5stack_atom/function/ir_lg_manual.yaml


esphome:
  comment: "Hall air-conditioner"


climate:
  - id: ac_climate
    platform: heatpumpir
    name: None
    protocol: panasonic_jke
    horizontal_default: left
    vertical_default: up
    min_temperature: 16
    max_temperature: 30
    on_state:
      - if:
          condition:
            lambda: 'return id(ac_climate).mode == climate::CLIMATE_MODE_OFF;'
          then:
            - logger.log: "Off"
            - light.turn_off:
                id: m5stack_atom_led
          else:
            - if:
                condition:
                  lambda: 'return id(ac_climate).mode == climate::CLIMATE_MODE_HEAT_COOL;'
                then:
                  - logger.log: "Auto"
                  - light.turn_on:
                      id: m5stack_atom_led
                      brightness: 100%
                      red: 100%
                      green: 0%
                      blue: 100%
                else:
                  - if:
                      condition:
                        lambda: 'return id(ac_climate).mode == climate::CLIMATE_MODE_COOL;'
                      then:
                        - logger.log: "Cooling"
                        - light.turn_on:
                            id: m5stack_atom_led
                            brightness: 100%
                            red: 0%
                            green: 0%
                            blue: 100%
                      else:
                        - if:
                            condition:
                              lambda: 'return id(ac_climate).mode == climate::CLIMATE_MODE_HEAT;'
                            then:
                              - logger.log: "Heating"
                              - light.turn_on:
                                  id: m5stack_atom_led
                                  brightness: 100%
                                  red: 100%
                                  green: 0%
                                  blue: 0%
                            else:
                              - if:
                                  condition:
                                    lambda: 'return id(ac_climate).mode == climate::CLIMATE_MODE_DRY;'
                                  then:
                                    - logger.log: "Drying"
                                    - light.turn_on:
                                        id: m5stack_atom_led
                                        brightness: 100%
                                        red: 100%
                                        green: 50%
                                        blue: 0%
                                  else:
                                    - logger.log: "Other"
                                    - light.turn_on:
                                        id: m5stack_atom_led
                                        brightness: 100%
                                        red: 100%
                                        green: 100%
                                        blue: 100%


select:
  - platform: template
    name: "Default Mode"
    id: ac_default_mode
    icon: "mdi:sun-snowflake-variant"
    options:
      - "COOL"
      - "HEAT"
      - "HEAT_COOL"
    initial_option: "HEAT_COOL"
    optimistic: true


binary_sensor:
  # Push button
  - id: !extend m5stack_atom_button
    on_press:
      - climate.control:
          id: ac_climate
          mode: "OFF"
    on_double_click:
      - climate.control:
          id: ac_climate
          mode: !lambda |-
            auto index = id(ac_default_mode).active_index();

            if (!index.has_value()) {
              return climate::CLIMATE_MODE_OFF;
            }

            switch (index.value()) {
              case 0:
                return climate::CLIMATE_MODE_COOL;

              case 1:
                return climate::CLIMATE_MODE_HEAT;

              case 2:
              default:
                return climate::CLIMATE_MODE_HEAT_COOL;
            }
