---

substitutions:
  # Device name and identifier (internal)
  device_name: kitchen-coffee
  device_id: kitchen_coffee

  # Friendly name for UI
  friendly_name: "Coffee Machine"

  # IP address
  device_ip: !secret ip_kitchen_coffee

  # Canned cycles
  wash_cycle_count: "5"
  wash_cycle_on_time: "10 sec"
  rinse_cycle_count: "10"
  rinse_cycle_on_time: "5 sec"
  cycle_off_time: "3 sec"

  # Auto-off timeout
  timeout: "70 min"


## Shared configuration
packages:
  # Core
  core: !include packages/core_mqtt.yaml

  # Remote access
  web_server: !include packages/web_server.yaml

  # Hardware specific
  hardware_base: !include packages/hardware/sonoff_pow_r2/base.yaml
  hardware_default: !include packages/hardware/sonoff_pow_r2/default_off.yaml
  hardware_status: !include packages/hardware/sonoff_pow_r2/status.yaml


esphome:
  comment: "Power monitor/control for coffee."

  on_boot:
    - priority: 600
      then:
        # Clear wash active status
        - binary_sensor.template.publish:
            id: ${device_id}_cycle_wash_active
            state: OFF
        
        # Turn off output timer
        - switch.turn_off: ${device_id}_relay_timed


button:
  - id: ${device_id}_run_wash
    platform: template
    name: "${friendly_name} Run Wash Cycle"
    icon: "mdi:silverware-clean"
    on_press:
      - script.execute: ${device_id}_cycle_wash
  
  - id: ${device_id}_run_rinse
    platform: template
    name: "${friendly_name} Run Rinse Cycle"
    icon: "mdi:silverware-clean"
    on_press:
      - script.execute: ${device_id}_cycle_rinse


binary_sensor:
  - id: !extend ${device_id}_button
    on_multi_click:
      - timing:
          - ON for at most 1s
          - OFF for at least 1s
        then:
          - if:
              condition:
                or:
                  - script.is_running: ${device_id}_cycle_wash
                  - script.is_running: ${device_id}_cycle_rinse
              then:
                - logger.log: "Aborting cycle"
                - script.stop: ${device_id}_cycle_wash
                - script.stop: ${device_id}_cycle_rinse
                - switch.turn_off: ${device_id}_relay_internal
              else:
                - switch.toggle: ${device_id}_relay_timed
          
      - timing:
        - ON for at most 1s
        - OFF for at most 1s
        - ON for at most 1s
        - OFF for at least 1s
        then:
          - script.execute: ${device_id}_cycle_wash
      
      - timing:
        - ON for at most 1s
        - OFF for at most 1s
        - ON for at most 1s
        - OFF for at most 1s
        - ON for at most 1s
        - OFF for at least 1s
        then:
          - script.execute: ${device_id}_cycle_rinse
  
  # Wash active flag
  - id: ${device_id}_cycle_wash_active
    platform: template
    name: "${friendly_name} Cleaning"
    icon: "mdi:silverware-clean"
    device_class: running

script:
  - id: ${device_id}_start_timeout
    mode: restart
    then:
      - switch.turn_on: ${device_id}_relay_internal
      - delay: ${timeout}
      - switch.turn_off: ${device_id}_relay_timed

  # Wash cycle
  - id: ${device_id}_cycle_wash
    mode: single
    then:
      - logger.log: "Wash start"
      - binary_sensor.template.publish:
            id: ${device_id}_cycle_wash_active
            state: ON
      - repeat:
          count: ${wash_cycle_count}
          then:
            - switch.turn_on: ${device_id}_relay_internal
            - delay: ${wash_cycle_on_time}
            - switch.turn_off: ${device_id}_relay_internal
            - delay: ${cycle_off_time}
      - binary_sensor.template.publish:
            id: ${device_id}_cycle_wash_active
            state: OFF
      - logger.log: "Wash complete"
  
  # Rinse cycle
  - id: ${device_id}_cycle_rinse
    mode: single
    then:
      - logger.log: "Rinse start"
      - binary_sensor.template.publish:
            id: ${device_id}_cycle_wash_active
            state: ON
      - repeat:
          count: ${rinse_cycle_count}
          then:
            - switch.turn_on: ${device_id}_relay_internal
            - delay: ${rinse_cycle_on_time}
            - switch.turn_off: ${device_id}_relay_internal
            - delay: ${cycle_off_time}
      - binary_sensor.template.publish:
            id: ${device_id}_cycle_wash_active
            state: OFF
      - logger.log: "Rinse complete"

switch:
  # Hide relay by default
  - id: !extend ${device_id}_relay
    internal: true
  
  - id: ${device_id}_relay_timed
    platform: template
    name: "${friendly_name} Power"
    icon: "mdi:coffee-maker"
    optimistic: true
    turn_on_action:
      - script.stop: ${device_id}_cycle_wash
      - script.stop: ${device_id}_cycle_rinse
      - script.execute: ${device_id}_start_timeout
    turn_off_action:
      - script.stop: ${device_id}_start_timeout
      - script.stop: ${device_id}_cycle_wash
      - script.stop: ${device_id}_cycle_rinse
      - switch.turn_off: ${device_id}_relay_internal
