---

substitutions:
  device_name: laundry-wash

  # Friendly name for UI
  friendly_name: Laundry Washing Machine

  # IP address
  device_ip: !secret ip_laundry_wash


packages:
  # Core
  core: !include packages/core_mqtt.yaml

  # Remote access
  web_server: !include packages/web_server.yaml

  # Hardware specific
  hardware_base: !include packages/hardware/sonoff_pow_r2/base.yaml
  hardware_default: !include packages/hardware/sonoff_pow_r2/force_on.yaml
  hardware_status: !include packages/hardware/sonoff_pow_r2/status.yaml

  # Function
  power_monitor: !include packages/hardware/sonoff_pow_r2/function/power_monitor.yaml


esphome:
  comment: "Power monitor for washing machine in the laundry."


binary_sensor:
  - platform: template
    name: "Running"
    icon: mdi:washing-machine
    device_class: running
    filters:
      - delayed_off: 7min
    lambda: |-
      if (id(sonoff_pow_r2_power).state > 4) {
        return true;
      } else {
        return false;
      }
