---

substitutions:
  # Device name and identifier (internal)
  device_name: lounge-tv
  device_icon: mdi:television

  # Friendly name for UI
  friendly_name: Lounge TV

  # IP address
  device_ip: !secret ip_lounge_tv


packages:
  # Core
  core: !include packages/core_mqtt.yaml

  # Remote access
  web_server: !include packages/web_server.yaml

  # Hardware specific
  hardware_base: !include packages/hardware/m5stack_atom/base.yaml
  hardware_status: !include packages/hardware/m5stack_atom/status.yaml
  hardware_ir: !include packages/hardware/m5stack_atom/ir.yaml

  # Utilities
  manual_ir: !include packages/hardware/m5stack_atom/function/ir_lg_manual.yaml


esphome:
  comment: "Lounge room TV remove"


script:
  - id: blink
    then:
      - light.turn_on:
          id: m5stack_atom_led
          brightness: 1.0
          color_brightness: 1.0
          red: 1.0
          green: 1.0
          blue: 1.0
          flash_length: 0.1s

  - id: tv_tx
    parameters:
      code: int
    then:
      - remote_transmitter.transmit_lg:
          data: !lambda return 0x00FE0000 | (((0xFF - code) & 0xFF) << 8) | (code & 0xFF);
          nbits: 32
      - script.execute: blink


button:
  - platform: template
    id: tv_power
    name: "Power"
    icon: "mdi:power"
    on_press:
      - script.execute:
          id: tv_tx
          code: 0x57

  - platform: template
    id: tv_power_cycle
    name: "Power Cycle"
    icon: "mdi:restart"
    on_press:
      - button.press: tv_power
      - delay: 5s
      - button.press: tv_power

  - platform: template
    id: tv_ch_up
    name: "Channel Up"
    icon: "mdi:menu-up-outline"
    on_press:
      - script.execute:
          id: tv_tx
          code: 0x27

  - platform: template
    id: tv_ch_down
    name: "Channel Down"
    icon: "mdi:menu-down-outline"
    on_press:
      - script.execute:
          id: tv_tx
          code: 0xA7

  - platform: template
    id: tv_vol_up
    name: "Volume Up"
    icon: "mdi:volume-plus"
    on_press:
      - script.execute:
          id: tv_tx
          code: 0x27

  - platform: template
    id: tv_vol_down
    name: "Volume Down"
    icon: "mdi:volume-minus"
    on_press:
      - script.execute:
          id: tv_tx
          code: 0xA7

  - platform: template
    id: tv_vol_mute
    name: "Mute"
    icon: "mdi:volume-mute"
    on_press:
      - script.execute:
          id: tv_tx
          code: 0x97

  - platform: template
    id: tv_up
    name: "Up"
    icon: "mdi:arrow-up"
    on_press:
      - script.execute:
          id: tv_tx
          code: 0xCF

  - platform: template
    id: tv_down
    name: "Down"
    icon: "mdi:arrow-down"
    on_press:
      - script.execute:
          id: tv_tx
          code: 0x4F

  - platform: template
    id: tv_left
    name: "Left"
    icon: "mdi:arrow-left"
    on_press:
      - script.execute:
          id: tv_tx
          code: 0x0F

  - platform: template
    id: tv_right
    name: "Right"
    icon: "mdi:arrow-right"
    on_press:
      - script.execute:
          id: tv_tx
          code: 0x8F

  - platform: template
    id: tv_enter
    name: "Enter"
    icon: "mdi:check"
    on_press:
      - script.execute:
          id: tv_tx
          code: 0xF7

  - platform: template
    id: tv_exit
    name: "Exit"
    icon: "mdi:close"
    on_press:
      - script.execute:
          id: tv_tx
          code: 0x37

  - platform: template
    id: tv_menu
    name: "Menu"
    icon: "mdi:menu"
    on_press:
      - script.execute:
          id: tv_tx
          code: 0x77

  - platform: template
    id: tv_source
    name: "Source"
    icon: "mdi:television"
    on_press:
      - script.execute:
          id: tv_tx
          code: 0xB7


binary_sensor:
  # Toggle power on button press
  - id: !extend m5stack_atom_button
    on_press:
      - button.press: tv_power
