---

# WiFi settings
wifi_ssid: "ssid"
wifi_password: "password"
wifi_fast_connect: true
wifi_domain: ".localdomain"

# LAN settings
ip_subnet: 255.255.255.0
ip_gateway: 192.168.0.1
ip_dns1: 192.168.0.1
ip_dns2: 0.0.0.0

# Device static IPs
ip_hall_aircon: 192.168.0.10
ip_lounge_tv: 192.168.0.11
ip_kitchen_coffee: 192.168.0.12
ip_powerpal: 192.168.0.13
ip_kitchen_gdo: 192.168.0.14
ip_void_catflap: 192.168.0.15
ip_nbn: 192.168.0.16
ip_laundry_washing: 192.168.0.17
ip_kitchen_dishwasher: 192.168.0.18
ip_void_power: 192.168.0.19
ip_study_power: 192.168.0.20
ip_frontdoor: 192.168.0.21

# SNTP
sntp_servers:
  - 192.168.0.1
  - 0.au.pool.ntp.org
  - 1.au.pool.ntp.org
sntp_tz: "Australia/Melbourne"

# Home assistant API (random key)
api_key: "h4HYoQADKZO3CLjfKyuqv5ameyT7dyrjRVcGRaGkziw="

# MQTT
mqtt_broker: 192.168.0.1
mqtt_username: "esphome"
mqtt_password: "password"

# OTA
ota_password: "password"

# Web server auth
web_server_auth_username: "admin"
web_server_auth_password: "password"

# iBeacon UUID (randon UUID)
ibeacon_uuid: "f974b750-b6d8-4a20-b644-c57121826c29"

ibeacon_major_downstairs: 1000
ibeacon_minor_downstairs_kitchen: 100
ibeacon_minor_downstairs_lounge: 101
ibeacon_minor_downstairs_void: 102
ibeacon_minor_downstairs_laundry: 103
ibeacon_minor_downstairs_workshop: 104

ibeacon_major_upstairs: 2000
ibeacon_minor_upstairs_chris_nina: 100
ibeacon_minor_upstairs_study: 101
ibeacon_minor_upstairs_xander: 102
ibeacon_minor_upstairs_bathroom: 103
ibeacon_minor_upstairs_toilet: 104
ibeacon_minor_upstairs_hall: 105

ibeacon_major_portable: 3000
ibeacon_minor_portable_chris_sunglasses_alpha: 100

ibeacon_major_external: 4000
ibeacon_minor_external_frontdoor: 100

# BLE
powerpal_mac_address: "00:00:00:00:00:00"
powerpal_pairing_code: 000000
