---

wifi_ssid: "ssid"
wifi_password: "password"
wifi_fast_connect: true
wifi_domain: ".localdomain"
ip_subnet: 255.255.255.0
ip_gateway: 192.168.0.1
ip_dns1: 192.168.0.1
ip_dns2: 0.0.0.0
ip_hall_aircon: 192.168.0.10
ip_lounge_tv: 192.168.0.11
ip_kitchen_coffee: 192.168.0.12
ip_powerpal: 192.168.0.13
ip_kitchen_gdo: 192.168.0.14
ip_void_catflap: 192.168.0.15
ip_nbn: 192.168.0.16
ip_laundry_washing: 192.168.0.17
ip_kitchen_dishwasher: 192.168.0.18
ip_void_power: 192.168.0.19
ip_study_power: 192.168.0.20
ip_frontdoor: 192.168.0.21
sntp_servers:
  - 192.168.0.1
  - 0.au.pool.ntp.org
  - 1.au.pool.ntp.org
sntp_tz: "Australia/Melbourne"
api_key: "h4HYoQADKZO3CLjfKyuqv5ameyT7dyrjRVcGRaGkziw="
mqtt_broker: 192.168.0.1
mqtt_username: "esphome"
mqtt_password: "password"
ota_password: "password"
web_server_auth_username: "admin"
web_server_auth_password: "password"
ibeacon_uuid: "f974b750-b6d8-4a20-b644-c57121826c29"
ibeacon_major_downstairs: 0
ibeacon_minor_downstairs_kitchen: 0
ibeacon_minor_downstairs_lounge: 0
ibeacon_minor_downstairs_void: 0
ibeacon_minor_downstairs_laundry: 0
ibeacon_minor_downstairs_workshop: 0
ibeacon_major_upstairs: 0
ibeacon_minor_upstairs_master: 0
ibeacon_minor_upstairs_study: 0
ibeacon_minor_upstairs_kids: 0
ibeacon_minor_upstairs_bathroom: 0
ibeacon_minor_upstairs_toilet: 0
ibeacon_minor_upstairs_hall: 0
ibeacon_major_portable: 0
ibeacon_minor_portable_etoast_sunglasses_alpha: 0
ibeacon_major_external: 0
ibeacon_minor_external_frontdoor: 0
powerpal_mac_address: "00:00:00:00:00:00"
powerpal_pairing_code: 000000
