---

substitutions:
  etoast_version: "v1.6.0"


## esphome Core Configuration
# https://esphome.io/components/esphome.html
esphome:
  # Prefix device name/hostname with esphome
  name: "esphome-${device_name}"

  # Name in front-end
  friendly_name: "${friendly_name}"

  # Device area
  # area: "${device_area}"

  # Project identifier
  project:
    name: "etoast.esphome"
    version: "${etoast_version}"

  # Current working esphome version
  min_version: "2023.3.2"


## Logger
# https://esphome.io/components/logger.html
logger:
  # Suppress some builtin logs
  logs:
    light: INFO


text_sensor:
  # Text sensor to display config version
  - platform: template
    name: "esphome Config"
    icon: "mdi:bread-slice"
    lambda: |-
      return {"${device_name} ${etoast_version}"};
    update_interval: 1h
    entity_category: diagnostic

  # Text sensor for esphome version
  - platform: version
    name: "esphome Version"
    entity_category: diagnostic
    hide_timestamp: true

  - platform: version
    name: "esphome Build"
    entity_category: diagnostic
