---

## MQTT
# https://esphome.io/components/mqtt.html
mqtt:
  id: core_mqtt
  broker: !secret mqtt_broker
  username: !secret mqtt_username
  password: !secret mqtt_password

  # Use MAC in UID generation
  discovery_unique_id_generator: mac
  # Use device identifiers in name generation
  discovery_object_id_generator: device_name
