---

## Wifi settings
# https://esphome.io/components/wifi.html
wifi:
  id: core_wifi
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: !secret wifi_fast_connect
  domain: !secret wifi_domain
  power_save_mode: none
  use_address: ${device_ip}
