---

## Wifi settings
# https://esphome.io/components/wifi.html
wifi:
  id: core_wifi
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: !secret wifi_fast_connect
  domain: !secret wifi_domain
  power_save_mode: none
  # use_address: ${device_ip}


sensor:
  ## WiFi Signal Sensor
  # https://esphome.io/components/sensor/wifi_signal.html
  - platform: wifi_signal
    id: wifi_sensor_signal
    <<: &wifi-sensor-common
      entity_category: diagnostic
      expire_after: 600s
    name: "WiFi Signal"
    update_interval: 300s


text_sensor:
  ## WiFi Info Text Sensor
  # https://esphome.io/components/text_sensor/wifi_info.html
  - platform: wifi_info
    ip_address:
      <<: &wifi-text-sensor-common
        entity_category: diagnostic
      name: "IP Address"
      id: wifi_sensor_ip

    ssid:
      <<: *wifi-text-sensor-common
      name: "Connected SSID"
      id: wifi_sensor_ssid
      disabled_by_default: true

    bssid:
      <<: *wifi-text-sensor-common
      name: "Connected BSSID"
      id: wifi_sensor_bssid
      disabled_by_default: true

    mac_address:
      <<: *wifi-text-sensor-common
      name: "MAC Address"
      id: wifi_sensor_mac
