---

## Base configuration for M5Stack Atom
esphome:
  platform: ESP32
  board: m5stack-core-esp32


## Serial configuration
improv_serial:


## Inputs
binary_sensor:
  # Push button
  - id: ${device_id}_button
    platform: gpio
    pin:
      number: 39
      inverted: true
    name: "${friendly_name} Button"
    disabled_by_default: true
    filters:
      - delayed_on: 100ms


## Lights
light:
  # RGB LED
  - id: ${device_id}_led
    platform: neopixelbus
    name: "${friendly_name} LED"
    type: GRB
    variant: WS2812
    pin: 27
    num_leds: 1
    disabled_by_default: true
