---

## Base configuration for M5Stack Atom
esp32:
  board: m5stack-core-esp32
  framework:
    type: esp-idf
    version: recommended


## Serial configuration
improv_serial:


## Inputs
binary_sensor:
  # Push button
  - id: m5stack_atom_button
    platform: gpio
    pin:
      number: 39
      inverted: true
    name: "Button"
    disabled_by_default: true
    filters:
      - delayed_on: 100ms


## Lights
light:
  # RGB LED
  - id: m5stack_atom_led
    platform: esp32_rmt_led_strip
    pin: 27
    num_leds: 1
    rmt_channel: 0
    chipset: WS2812
    rgb_order: GRB
    name: "LED"
    disabled_by_default: true
