---

## Display status on RGB LED
# Flash red when no WiFi
# Flash yellow when no connection to home-assistant/MQTT
binary_sensor:
  - id: ${device_id}_status
    platform: status
    name: "${friendly_name} Connection Status"
    internal: true


ota:
  on_begin:
    then:
      - light.turn_on:
          id: ${device_id}_led
          brightness: 0.1
          color_brightness: 0.1
          red: 0.0
          green: 0.0
          blue: 1.0


interval:
  # Turn blink LED when idle
  - interval: 5s
    then:
      - if:
          condition:
            not:
              wifi.connected:
          then:
            - light.turn_on:
                id: ${device_id}_led
                brightness: 0.1
                color_brightness: 0.1
                red: 1.0
                green: 0.0
                blue: 0.0
                flash_length: 0.1s
          else:
            - if:
                condition:
                  not:
                    binary_sensor.is_on: ${device_id}_status
                then:
                  - light.turn_on:
                      id: ${device_id}_led
                      brightness: 0.1
                      color_brightness: 0.1
                      red: 1.0
                      green: 1.0
                      blue: 0.0
                      flash_length: 0.1s
