---

name: "esphome CI"


on:
  push:
    paths:
      - .github/workflows/ci.yaml
      - config/**/*.yaml
  pull_request:
    paths:
      - .github/workflows/ci.yaml
      - config/**/*.yaml
  workflow_dispatch:


jobs:
  check_config:
    name: "Validate config (${{ matrix.esphome-version }})"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        esphome-version:
          - stable
          - beta
    steps:
      - name: "Checkout configuration"
        uses: actions/checkout@v3

      - name: "Run configuration test"
        shell: "bash"
        run: |
          if [ ! -f "${GITHUB_WORKSPACE}/config/secrets.yaml" ]; then
            cp "${GITHUB_WORKSPACE}/config/secrets.ci.yaml" "${GITHUB_WORKSPACE}/config/secrets.yaml"
          fi

          for file in $(find "${GITHUB_WORKSPACE}/config" -maxdepth 1 -type f -name "*.yaml" -not -name "secrets*.yaml" -printf "%f\n"); do
            echo "Testing ${file}"

            docker run \
            --rm \
            --name "esphome_config" \
            -v "${GITHUB_WORKSPACE}/config:/config" \
            "ghcr.io/esphome/esphome:${{ matrix.esphome-version }}" \
            config "${file}"
          done
      
      - name: "Run compilation test"
        shell: "bash"
        run: |
          for file in $(find "${GITHUB_WORKSPACE}/config" -maxdepth 1 -type f -name "*.yaml" -not -name "secrets*.yaml" -printf "%f\n"); do
            echo "Building ${file}"
            
            docker run \
            --rm \
            --name "esphome_compile" \
            -v "${GITHUB_WORKSPACE}/config:/config" \
            "ghcr.io/esphome/esphome:${{ matrix.esphome-version }}" \
            compile "${file}"
          done
