---

name: "esphome CI"


on:
  push:
    paths:
      - .github/workflows/ci.yaml
      - config/**/*.yaml
  pull_request:
    paths:
      - .github/workflows/ci.yaml
      - config/**/*.yaml
  workflow_dispatch:


jobs:
  check_config:
    name: "Validate config (${{ matrix.esphome-version }})"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        esphome-version:
          - stable
          - beta
    steps:
      - name: "Checkout configuration"
        uses: actions/checkout@v3

      - name: "Get esphome version"
        id: esphome-version
        shell: "bash"
        run: |
          version=$( \
            docker run \
            --rm \
            --name "esphome_config" \
            "ghcr.io/esphome/esphome:${{ matrix.esphome-version }}" \
            version \
          )

          echo "::notice::version=${version}"
          echo "esphome_version=$(echo "${version}" | cut -d "" -f 2)" >> "$GITHUB_ENV"

      - name: "Run configuration test"
        id: esphome-config
        shell: "bash"
        run: |
          if [ ! -f "${GITHUB_WORKSPACE}/config/secrets.yaml" ]; then
            cp "${GITHUB_WORKSPACE}/config/secrets.ci.yaml" "${GITHUB_WORKSPACE}/config/secrets.yaml"
          fi

          device_files=$( \
            find \
            "${GITHUB_WORKSPACE}/config" \
            -maxdepth 1 \
            -type f \
            -name "*.yaml" \
            -not -name "secrets*.yaml" \
            -printf "%f\n" \
          )

          for file in ${device_files}; do
            echo "Testing ${file}"

            docker run \
            --rm \
            --name "esphome_config" \
            -v "${GITHUB_WORKSPACE}/config:/config" \
            "ghcr.io/esphome/esphome:${{ matrix.esphome-version }}" \
            config "${file}"
          done

      - name: Cache esphome/platformio environment
        id: esphome-env
        uses: actions/cache@v3
        with:
          path: esphome
          key: esphome-env-${{ env.esphome_version }}

      - name: "Run compilation test"
        id: esphome-compile
        shell: "bash"
        run: |
          device_files=$( \
            find \
            "${GITHUB_WORKSPACE}/config" \
            -maxdepth 1 \
            -type f \
            -name "*.yaml" \
            -not -name "secrets*.yaml" \
            -printf "%f\n" \
          )

          for file in ${device_files}; do
            echo "Building ${file}"

            docker run \
            --rm \
            --name "esphome_compile" \
            -v "${GITHUB_WORKSPACE}/config:/config" \
            -v "${GITHUB_WORKSPACE}/esphome:/config/.esphome" \
            "ghcr.io/esphome/esphome:${{ matrix.esphome-version }}" \
            compile "${file}"
          done
