---

name: "esphome CI"


on:
  push:
    paths:
      - .github/workflows/esphome.yaml
      - config/**/*.yaml
  pull_request:
    paths:
      - .github/workflows/esphome.yaml
      - config/**/*.yaml
  workflow_dispatch:


jobs:
  check_config:
    name: "Validate config (${{ matrix.esphome-version }})"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        esphome-version:
          - stable
          - beta
    steps:
      - name: "Checkout configuration"
        uses: actions/checkout@v3

      - name: "Get esphome version"
        id: esphome-version
        shell: "bash"
        run: |
          version=$( \
            docker run \
            --rm \
            --name "esphome_config" \
            "ghcr.io/esphome/esphome:${{ matrix.esphome-version }}" \
            version | tail -n 1 \
          )

          echo "::notice title=Version Output::${version}"
          echo "esphome_version=$(echo "${version}" | cut -d "" -f 2)" >> "$GITHUB_ENV"

      - name: Cache esphome environment
        id: esphome-env
        uses: actions/cache@v3
        with:
          path: esphome
          key: esphome-env-${{ env.esphome_version }}

      - name: "Run compilation test"
        id: esphome-compile
        shell: "bash"
        run: |
          device_files=$( \
            find \
            "${GITHUB_WORKSPACE}/config" \
            -maxdepth 1 \
            -type f \
            -name "*.yaml" \
            -not -name "secrets*.yaml" \
            -printf "%f\n" \
          )

          for file in ${device_files}; do
            echo "Building ${file}"

            docker run \
            --rm \
            --name "esphome_compile" \
            -v "${GITHUB_WORKSPACE}/config:/config" \
            -v "${GITHUB_WORKSPACE}/esphome:/config/.esphome" \
            "ghcr.io/esphome/esphome:${{ matrix.esphome-version }}" \
            compile "${file}"
          done
